### ISSUE TITLE
crtags is giving 'TypeError: ('__init__() takes exactly 2 arguments (1 given)', <class 'clang.cindex.LibclangError'>, ())' on ubuntu 14.04

### ISSUE THREAD

**Issue by harshal-dhumal** [crange/crange#7]
stack trace

```
$ crtags -v ~/curl-7.41.0/

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 380, in _handle_results
    task = get()
TypeError: ('__init__() takes exactly 2 arguments (1 given)', <class 'clang.cindex.LibclangError'>, ())
```

**Comment by ducalpha** [comment]
I got the same error on Ubuntu 12.04. I tried harshal-dhumal's fork, too, but it also got the same error :(

**Comment by gnurag** [comment]
I haven't been able to figure out how to capture Keyboard interrupt from child processes. One way I see is to remove all multiprocessing code.

**Comment by wyklq** [comment]
I got the same error on several systems (CentOS 6, Fedora 22 etc.) where no clang was installed.
Later I figured out that, it actually has a dependency with "clang", which cannot be resolved by "pip install crange". 
BTW. the "python setup.py install" didn't work under python 2.

**Comment by glenn-horton-smith** [comment]
Note that the pypi versions of clang since 3.7 declare themselves to be "Obsolete" according to the package descriptions on https://pypi.python.org/pypi/clang/ (3.8, 3.9.post1, 4.0.post1):

> OBSOLETE. LLVM-CLANG NOW PUBLISHES PYTHON PACKAGE.
> JUST ADD THE OFFICIAL llvm-3.7 repo in your apt.

A workaround for me was to uninstall the pip package for clang (which got installed when I did "pip install crange") and install python-clang-3.9.  Since I'm using Linux Mint 17 (rosa), I did that by
`sudo apt-get install python-clang-3.9`
(The same package exists on Ubuntu 14 (trusty) and Ubuntu 16 (xenial).)

After doing that, crange works fine for me.  I hope that workaround helps someone else too.

I'm not sure if the fundamental issue is that clang in the official repos is somehow "better" than in pypi, or that something has changed in clang 4.0 vs 3.9 and earlier.  When I tried to install using only pip, it naturally grabbed the latest clang in pypi, which is "4.0.post1".  When I installed clang using "apt", 3.9 was the latest available, so I used that.
