### ISSUE TITLE
First time use error

### ISSUE THREAD

**Issue by Werror** [crange/crange#9]
Installed using git clone and python script
I get the following error: I am very interested in this and kindly asking for help
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 376, in _handle_results
    task = get()
TypeError: ('__init**() takes exactly 2 arguments (1 given)', <class 'clang.cindex.LibclangError'>, ())

**Comment by nrnrnr** [comment]
I get the same issue using `sudo pip install crange`.
